{% set name = "os_command_py" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 321d2c0e4c2e547f7e989ef857cc88cebf6900ff2b638ed712072df39d7c16ec

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - os_command_py
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest --pyargs os_command_py --doctest-modules

about:
  home: "https://github.com/samuelmurail/os_command_py"
  license: "GPL-2.0-only"
  license_file: LICENSE
  summary: "os_command_py is a python library allowing a simplified use of the OS commands."
  doc_url: "https://os-command-py.readthedocs.io/en/latest/"

extra:
  recipe-maintainers:
    - samuelmurail
